# Generated by Django 3.1.2 on 2021-05-07 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepstreamServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(blank=True, max_length=120)),
                ('mac_addr', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('online', 'On-line'), ('online-idle', 'On-line Idle'), ('online-in-error', 'On-line In Error'), ('online-streaming', 'On-line Streaming'), ('offline', 'Off-line')], default='offline', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_echo_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeepstreamLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deepstream_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deepstream_servers.deepstreamserver')),
            ],
        ),
        migrations.CreateModel(
            name='DeepstreamDiagnostics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_utilization', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gpu_utilization', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('memory_usage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gpu_memory_usage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.IntegerField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('deepstream_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deepstream_servers.deepstreamserver')),
            ],
        ),
    ]
