# Generated by Django 3.1.2 on 2021-04-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepstream_servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepstreamserver',
            name='mac_addr',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
