# Generated by Django 3.1.2 on 2021-04-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepstream_servers', '0002_auto_20210430_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepstreamserver',
            old_name='last_response_received_at',
            new_name='last_echo_at',
        ),
    ]
