# Generated by Django 3.1.2 on 2021-05-03 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20210429_1136'),
        ('deepstream_servers', '0003_auto_20210430_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepstreamserver',
            name='block',
        ),
        migrations.AddField(
            model_name='deepstreamserver',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
    ]
