# Generated by Django 2.2.10 on 2020-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_organization_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_sub_organization_admin',
            field=models.BooleanField(default=False),
        ),
    ]
