# Generated by Django 2.2.16 on 2020-10-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='authority',
            field=models.IntegerField(default=-1),
        ),
    ]
