# Generated by Django 3.1.2 on 2021-02-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210129_1528'),
        ('users', '0002_auto_20210203_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
