# Generated by Django 2.2.10 on 2020-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0002_auto_20201017_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='authorized_locations',
            field=models.ManyToManyField(blank=True, null=True, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
    ]
