# Generated by Django 2.2.10 on 2020-10-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201017_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_organization_admin',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_sub_organization_admin',
        ),
    ]
