# Generated by Django 3.1.2 on 2020-10-27 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201027_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
