# Generated by Django 3.1.2 on 2020-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_uuid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
