# Generated by Django 3.1.2 on 2020-10-27 13:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201027_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', users.models.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
