# Generated by Django 3.1.2 on 2021-05-20 10:59

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('authority', models.PositiveIntegerField()),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_group_set', related_query_name='user_group', to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'user group',
                'verbose_name_plural': 'user groups',
            },
            managers=[
                ('objects', user_auth.models.UserGroupManager()),
            ],
        ),
    ]
