# Generated by Django 3.1.2 on 2021-05-18 05:34

from django.db import migrations, models
import django.db.models.deletion
import app_organizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_organizations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('authority', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='app_organizations.apporganization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='organization_group_set',
                 related_query_name='organization_group', to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'organization group',
                'verbose_name_plural': 'organization groups',
                'unique_together': {('name', 'organization')},
            },
            managers=[
                ('objects', app_organizations.models.OrganizationGroupManager()),
            ],
        ),
    ]
