# Generated by Django 3.1.2 on 2021-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Unknown', max_length=125),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'parent')},
        ),
    ]
