# Generated by Django 2.2.10 on 2020-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='suborganization',
            old_name='title',
            new_name='name',
        ),
    ]
