# Generated by Django 2.2.10 on 2020-10-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='description',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
