# Generated by Django 3.1.2 on 2021-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210429_1121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='unique_with_parent'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(parent=None), fields=('name',), name='unique_without_parent'),
        ),
    ]
