# Generated by Django 2.2.10 on 2020-10-11 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20201011_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Unknown', max_length=120)),
                ('desc', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
    ]
