# Generated by Django 3.1.2 on 2021-04-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210409_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='desc',
        ),
    ]
