# Generated by Django 2.2.10 on 2020-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_suborganization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(blank='Unknown', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='suborganization',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suborganization',
            name='title',
            field=models.CharField(default='Unknown', max_length=120, unique=True),
        ),
    ]
