# Generated by Django 2.2.10 on 2020-10-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20201011_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(default='Unknown', max_length=120, unique=True),
        ),
    ]
