# Generated by Django 2.2.10 on 2020-10-11 16:36

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_block_coordinate_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(default='Main', max_length=120, unique=True)),
                ('ip_addr', models.CharField(max_length=120)),
                ('coords', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Block')),
            ],
        ),
    ]
