# Generated by Django 3.1.2 on 2021-04-08 06:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('deepstream_servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(
                    default='Main', max_length=125, unique=True)),
                ('ip_addr', models.CharField(max_length=120)),
                ('block', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='locations.block')),
                ('deepstream_server', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='deepstream_servers.deepstreamserver')),
            ],
        ),
    ]
