# Generated by Django 3.1.2 on 2021-05-07 19:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measurement_frames', '0001_initial'),
        ('deepstream_servers', '__first__'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=120)),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=2)),
                ('point_coords_in_frame', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=8)),
                ('point_coords_in_image', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=8)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.block')),
                ('deepstream_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deepstream_servers.deepstreamserver')),
                ('measurement_frame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement_frames.measurementframe')),
            ],
        ),
    ]
