# Generated by Django 3.1.2 on 2021-05-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deepstream_servers', '0003_auto_20210430_0950'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='deepstream_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='deepstream_servers.deepstreamserver'),
        ),
    ]
