# Generated by Django 2.2.10 on 2020-10-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip_addr2',
            field=models.CharField(default='rtsp://', max_length=120),
            preserve_default=False,
        ),
    ]
