# Generated by Django 3.1.2 on 2021-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='coords_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='coords_y',
            field=models.FloatField(default=0.0),
        ),
    ]
