# Generated by Django 3.1.2 on 2021-04-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_measurementframe_is_global'),
        ('cameras', '0002_auto_20210405_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='coords_x',
            new_name='p0_coord_in_frame_x',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='coords_y',
            new_name='p0_coord_in_frame_y',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='place_name',
        ),
        migrations.AddField(
            model_name='camera',
            name='measurement_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.measurementframe'),
        ),
        migrations.AddField(
            model_name='camera',
            name='p0_coord_in_image_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p0_coord_in_image_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p1_coord_in_frame_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p1_coord_in_frame_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p1_coord_in_image_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p1_coord_in_image_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p2_coord_in_frame_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p2_coord_in_frame_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p2_coord_in_image_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p2_coord_in_image_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p3_coord_in_frame_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p3_coord_in_frame_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p3_coord_in_image_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='camera',
            name='p3_coord_in_image_y',
            field=models.FloatField(default=0.0),
        ),
    ]
