# Generated by Django 2.2.10 on 2020-10-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_ip_addr2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ip_addr',
        ),
    ]
