# Generated by Django 3.1.2 on 2021-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_auto_20210405_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='p0_coord_in_frame_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p0_coord_in_frame_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p0_coord_in_image_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p0_coord_in_image_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p1_coord_in_frame_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p1_coord_in_frame_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p1_coord_in_image_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p1_coord_in_image_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p2_coord_in_frame_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p2_coord_in_frame_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p2_coord_in_image_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p2_coord_in_image_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p3_coord_in_frame_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p3_coord_in_frame_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p3_coord_in_image_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='p3_coord_in_image_y',
            field=models.IntegerField(default=0),
        ),
    ]
