# Generated by Django 2.2.10 on 2020-10-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_remove_camera_ip_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ip_addr2',
            new_name='ip_addr',
        ),
    ]
