# Generated by Django 3.1.2 on 2021-04-08 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_auto_20210405_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=8),
        ),
    ]
