# Generated by Django 3.1.2 on 2021-04-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20210409_1435'),
        ('deepstream_servers', '0002_auto_20210409_1435'),
        ('cameras', '0005_camera_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.block'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='deepstream_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deepstream_servers.deepstreamserver'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='measurement_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.measurementframe'),
        ),
    ]
