# Generated by Django 3.1.2 on 2021-04-15 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_auto_20210409_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=2),
        ),
    ]
