# Generated by Django 3.1.2 on 2021-04-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement_frames', '0001_initial'),
        ('cameras', '0007_auto_20210415_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='measurement_frame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='measurement_frames.measurementframe'),
        ),
    ]
