# Generated by Django 3.1.2 on 2021-05-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=150)),
                ('pixel_pose_x', models.IntegerField()),
                ('pixel_pose_y', models.IntegerField()),
                ('pixel_pose_theta', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.block')),
            ],
        ),
        migrations.AddConstraint(
            model_name='measurementframe',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name', 'block'), name='unique_frame_if_not_deleted'),
        ),
    ]
