# Generated by Django 3.1.2 on 2021-04-15 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0010_remove_measurementframe_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('pixel_pose_x', models.IntegerField(default=0)),
                ('pixel_pose_y', models.IntegerField(default=0)),
                ('pixel_pose_theta', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.block')),
            ],
        ),
    ]
