# Generated by Django 3.1.2 on 2021-03-18 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_addr', models.CharField(max_length=120)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.block')),
            ],
        ),
    ]
