# Generated by Django 3.1.2 on 2021-05-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import organizations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(help_text='The name of the organization', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('slug', organizations.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from='name', unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='organizations/outlets/avatars')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='app_organizations.apporganization')),
            ],
            options={
                'verbose_name': 'outlet',
                'verbose_name_plural': 'outlets',
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='OutletUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='outlets.outlet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets_outletuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'outlet user',
                'verbose_name_plural': 'outlet users',
                'proxy': False,
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='OutletOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='outlets.outlet')),
                ('organization_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='outlets.outletuser')),
            ],
            options={
                'verbose_name': 'outlet owner',
                'verbose_name_plural': 'outlet owners',
                'proxy': False,
            },
        ),
        migrations.CreateModel(
            name='OutletInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('guid', models.UUIDField(editable=False)),
                ('invitee_identifier', models.CharField(help_text='The contact identifier for the invitee, email, phone number, social media handle, etc.', max_length=1000)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets_outletinvitation_sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlets_outletinvitation_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_invites', to='outlets.outlet')),
            ],
            options={
                'verbose_name': 'outlet invitation',
                'verbose_name_plural': 'outlet invitations',
                'proxy': False,
            },
        ),
        migrations.AddField(
            model_name='outlet',
            name='users',
            field=models.ManyToManyField(related_name='outlets_outlet', through='outlets.OutletUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
