# Generated by Django 3.1.2 on 2021-05-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0003_auto_20210518_0747'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='outlets', to='app_organizations.apporganization'),
        ),
    ]
