# Generated by Django 3.1.2 on 2021-05-20 12:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSDiagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('cpu_utilization', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gpu_utilization', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('memory_usage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gpu_memory_usage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('temperature', models.IntegerField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('ip_addr', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('online', 'On-line'), ('online-idle', 'On-line Idle'), ('online-in-error', 'On-line In Error'), ('online-streaming', 'On-line Streaming'), ('offline', 'Off-line')], default='offline', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_echo_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dsserver',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('ip_addr',), name='unique_ds_if_not_deleted'),
        ),
        migrations.AddField(
            model_name='dslogentry',
            name='ds_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ds_servers.dsserver'),
        ),
        migrations.AddField(
            model_name='dsdiagnostics',
            name='ds_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ds_servers.dsserver'),
        ),
    ]
