# Generated by Django 3.1.2 on 2021-05-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ds_servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsserver',
            name='connected_at',
        ),
    ]
