# Generated by Django 3.1.2 on 2021-05-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apporganization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='apporganizationinvitation',
            options={'verbose_name': 'organization invitation', 'verbose_name_plural': 'organization invitations'},
        ),
        migrations.AlterModelOptions(
            name='apporganizationowner',
            options={'verbose_name': 'organization owner', 'verbose_name_plural': 'organization owners'},
        ),
        migrations.AlterModelOptions(
            name='apporganizationuser',
            options={'verbose_name': 'organization user', 'verbose_name_plural': 'organization users'},
        ),
    ]
