# Generated by Django 3.1.2 on 2021-05-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0002_auto_20210518_0728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apporganization',
            options={'ordering': ['name'], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='apporganizationuser',
            options={'ordering': ['organization', 'user'], 'verbose_name': 'organization user', 'verbose_name_plural': 'organization users'},
        ),
    ]
