# Generated by Django 3.1.2 on 2021-04-05 06:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Block', max_length=150)),
                ('floor_map', models.ImageField(
                    blank=True, null=True, upload_to='maps')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('is_global', models.BooleanField(default=False)),
                ('block', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='locations.block')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('location', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'unique_together': {('number', 'location')},
            },
        ),
        migrations.AddField(
            model_name='block',
            name='floor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='locations.floor'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('name', 'floor')},
        ),
    ]
