# Generated by Django 3.1.2 on 2020-10-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='desc',
        ),
    ]
