# Generated by Django 2.2.10 on 2020-10-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_suborganization'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sub_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.SubOrganization'),
        ),
        migrations.DeleteModel(
            name='SubLocation',
        ),
    ]
