# Generated by Django 3.1.2 on 2021-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
