# Generated by Django 3.1.2 on 2021-04-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20210405_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='coordinate_frame',
        ),
        migrations.RemoveField(
            model_name='block',
            name='size',
        ),
        migrations.RemoveField(
            model_name='measurementframe',
            name='pose_in_global',
        ),
        migrations.AddField(
            model_name='block',
            name='coordinate_frame_theta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='coordinate_frame_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='coordinate_frame_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='size_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='size_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurementframe',
            name='pose_in_global_theta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurementframe',
            name='pose_in_global_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='measurementframe',
            name='pose_in_global_y',
            field=models.FloatField(default=0.0),
        ),
    ]
