# Generated by Django 3.1.2 on 2021-02-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210204_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(default='Main Block', max_length=150),
        ),
    ]
