# Generated by Django 2.2.10 on 2020-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20201011_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='number',
        ),
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='Unknown', max_length=120, unique=True),
        ),
    ]
