# Generated by Django 3.1.2 on 2021-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210519_1052'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_if_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name',), name='unique_if_not_deleted'),
        ),
    ]
