# Generated by Django 3.1.2 on 2021-04-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20210405_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='coordinate_frame_theta',
            new_name='pixels_to_m_x',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='coordinate_frame_x',
            new_name='pixels_to_m_y',
        ),
        migrations.RemoveField(
            model_name='block',
            name='coordinate_frame_y',
        ),
        migrations.RemoveField(
            model_name='block',
            name='size_x',
        ),
        migrations.RemoveField(
            model_name='block',
            name='size_y',
        ),
    ]
