# Generated by Django 3.1.2 on 2021-04-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210405_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementframe',
            old_name='pose_in_global_theta',
            new_name='pixel_pose_theta',
        ),
        migrations.RenameField(
            model_name='measurementframe',
            old_name='pose_in_global_x',
            new_name='pixel_pose_x',
        ),
        migrations.RenameField(
            model_name='measurementframe',
            old_name='pose_in_global_y',
            new_name='pixel_pose_y',
        ),
    ]
