# Generated by Django 3.1.2 on 2021-02-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210204_1046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('name', 'floor')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('number', 'location')},
        ),
    ]
