# Generated by Django 3.1.2 on 2021-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210519_1053'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_if_not_deleted',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name', 'floor'), name='unique_block_if_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('number', 'location'), name='unique_floor_if_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name',), name='unique_location_if_not_deleted'),
        ),
    ]
