# Generated by Django 2.2.10 on 2020-10-11 16:14

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20201011_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='coordinate_frame',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
