# Generated by Django 3.1.2 on 2021-04-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210405_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementframe',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
