# Generated by Django 3.1.2 on 2021-03-26 10:06

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210208_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='size',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
