# Generated by Django 3.1.2 on 2021-04-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_measurementframe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementframe',
            name='is_global',
        ),
    ]
