# Generated by Django 2.2.10 on 2020-10-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_block_coordinate_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_map',
            field=models.ImageField(blank=True, null=True, upload_to='assets/maps'),
        ),
        migrations.AddField(
            model_name='block',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
