# Generated by Django 2.2.10 on 2020-10-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20201012_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_map',
            new_name='floor_map',
        ),
        migrations.RemoveField(
            model_name='block',
            name='map_url',
        ),
    ]
