# Generated by Django 3.1.2 on 2021-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_measurementframe_is_global'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementframe',
            name='pixel_pose_theta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurementframe',
            name='pixel_pose_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='measurementframe',
            name='pixel_pose_y',
            field=models.IntegerField(default=0),
        ),
    ]
