# Generated by Django 3.1.2 on 2021-04-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210409_1435'),
        ('locations', '0008_auto_20210405_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.floor'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='measurementframe',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.block'),
        ),
    ]
