# Generated by Django 3.1.2 on 2021-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20210409_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementframe',
            name='block',
        ),
    ]
