# Generated by Django 3.1.2 on 2021-04-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_remove_measurementframe_block'),
        ('cameras', '0008_auto_20210415_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementFrame',
        ),
    ]
