# Generated by Django 3.1.2 on 2021-04-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_delete_measurementframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(),
        ),
    ]
