# Generated by Django 3.1.2 on 2021-04-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20210416_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='location',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(editable=False),
        ),
    ]
