# Generated by Django 3.1.2 on 2021-04-19 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20210416_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
