# Generated by Django 3.1.2 on 2021-04-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20210419_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='floor_map',
            field=models.ImageField(default='/media/maps/wing_l.png', upload_to='maps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='block',
            name='pixels_to_m_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='pixels_to_m_y',
            field=models.FloatField(),
        ),
    ]
